apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-village-dev

resources:
  - ../../base
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: latest

labels:
  - includeSelectors: false
    pairs:
      tenant: opsera
      app: village
      environment: dev
      managed-by: opsera-c2c
