apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-village-dev

resources:
  - ../../base
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/village
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/village
    newTag: 

labels:
  - includeSelectors: false
    pairs:
      tenant: opsera
      app: village
      environment: dev
      managed-by: opsera-c2c
